#!/bin/bash

# SocRob autocompletion functions

# autocompletion for clean_pkg_from_ws function (cleans autogenerated files for pkgs)
function _roscomplete_packages {
    local arg opts
    arg="${COMP_WORDS[COMP_CWORD]}"

    if [[ $COMP_CWORD == 1 ]]; then
        _roscomplete_pkg "${arg}"
    elif [[ $COMP_CWORD == 0 ]]; then
        opts=`rospack list-names`
        COMPREPLY=($(compgen -W "$opts" -- ${arg}))
    fi
}
complete -F "_roscomplete_packages" "clean_pkg_from_ws"

# autocompletion for the switch_arm_ctrl function (to switch simulated arm between controllers)
function _complete_switch_arm_ctrl {
    local arg opts
    arg="${COMP_WORDS[COMP_CWORD]}"
    if [[ $COMP_CWORD < 2 ]]; then
        opts='trajectory position velocity'
        COMPREPLY=($(compgen -W "$opts" -- ${arg}))
    fi
}
complete -F "_complete_switch_arm_ctrl" "switch_arm_sim_ctrl"

# new autocompletion functions should be added here below (leave Enrico alias at the end)


# Enrico autocompletion functions
# (partially taken from: https://github.com/cykerway/complete-alias)
# -------------------------------

# Use-alias flag. (used for Enrico alias rr -> rosrun, rs -> rosservice, etc.)
_use_alias=1

# Disable the use of alias for a command. (used for Enrico alias rr -> rosrun, rs -> rosservice, etc.)
_disable_alias () {
    local cmd="$1"

    # Remove completion for this command.
    complete -r "$cmd"

    # Reset static completions.
    #
    # We don't know the original no-alias completion for $cmd because it has
    # been overwritten by the alias completion function. What we do here is that
    # we reset all static completions to those in vanilla bash_completion. This
    # may be an overkill becase we only need to reset completion for $cmd, but
    # it works.
    complete -u groups slay w sux
    complete -A stopped -P '"%' -S '"' bg
    complete -j -P '"%' -S '"' fg jobs disown
    complete -v readonly unset
    complete -A setopt set
    complete -A shopt shopt
    complete -A helptopic help
    complete -a unalias
    complete -A binding bind
    complete -c command type which
    complete -b builtin
    complete -F _service service
    complete -F _known_hosts traceroute traceroute6 tracepath tracepath6 \
        fping fping6 telnet rsh rlogin ftp dig mtr ssh-installkeys showmount
    complete -F _command aoss command do else eval exec ltrace nice nohup \
        padsp then time tsocks vsound xargs
    complete -F _root_command fakeroot gksu gksudo kdesudo really
    complete -F _longopt a2ps awk base64 bash bc bison cat chroot colordiff cp \
        csplit cut date df diff dir du enscript env expand fmt fold gperf \
        grep grub head irb ld ldd less ln ls m4 md5sum mkdir mkfifo mknod \
        mv netstat nl nm objcopy objdump od paste pr ptx readelf rm rmdir \
        sed seq sha{,1,224,256,384,512}sum shar sort split strip sum tac tail tee \
        texindex touch tr uname unexpand uniq units vdir wc who
    complete -F _minimal ''
    complete -D -F _completion_loader

    # Reset _use_alias flag.
    _use_alias=0
}

# Enable the use of alias for a command. (used for Enrico alias rr -> rosrun, rs -> rosservice, etc.)
_enable_alias () {
    local cmd="$1"

    # Set completion for this command.
    complete -F _complete_alias "$cmd"

    # Set _use_alias flag.
    _use_alias=1
}

# Expand the first command as an alias, stripping all leading redirections. (used for Enrico alias rr -> rosrun, rs -> rosservice, etc.)
_expand_alias () {
    local alias_name="${COMP_WORDS[0]}"
    local alias_namelen="${#alias_name}"
    local alias_array=( $(alias "$alias_name" | sed -r 's/[^=]*=//' | xargs) )
    local alias_arraylen="${#alias_array[@]}"
    local alias_str="${alias_array[*]}"
    local alias_strlen="${#alias_str}"

    # Rewrite current completion context by expanding alias.
    COMP_WORDS=(${alias_array[@]} ${COMP_WORDS[@]:1})
    (( COMP_CWORD+=($alias_arraylen-1) ))
    COMP_LINE="$alias_str""${COMP_LINE:$alias_namelen}"
    (( COMP_POINT+=($alias_strlen-$alias_namelen) ))

    # Strip leading redirections in alias-expanded command line.
    local redir="@(?([0-9])<|?([0-9&])>?(>)|>&)"
    while [[ "${#COMP_WORDS[@]}" -gt 0 && "${COMP_WORDS[0]}" == $redir* ]]; do
        local word="${COMP_WORDS[0]}"
        COMP_WORDS=(${COMP_WORDS[@]:1})
        (( COMP_CWORD-- ))
        local linelen="${#COMP_LINE}"
        COMP_LINE="${COMP_LINE#$word+( )}"
        (( COMP_POINT-=($linelen-${#COMP_LINE}) ))
    done
}

# alias completion function. (used for Enrico alias rr -> rosrun, rs -> rosservice, etc.)
_complete_alias () {
    local cmd="${COMP_WORDS[0]}"

    if [[ "$_use_alias" -eq 1 ]]; then
        _expand_alias
    fi
    _disable_alias "$cmd"
    _command_offset 0
    _enable_alias "$cmd"
}

# autocompletion for rosbash alias (e.g. rr -> rosrun) (used for Enrico alias rr -> rosrun, rs -> rosservice, etc.)
complete -F _complete_alias p
complete -F _complete_alias r
complete -F _complete_alias rc
complete -F _complete_alias rt
complete -F _complete_alias rs
complete -F _complete_alias rn
complete -F _complete_alias rl
complete -F _complete_alias rr
complete -F _complete_alias rb
complete -F _complete_alias rcd
complete -F _complete_alias sai
